import type {
  BessAssumptions,
  HybridAssumptions,
  PriceAssumptions,
  SolarAssumptions,
  WindAssumptions,
} from "./types";

export const DEFAULT_PRICE_ASSUMPTIONS: PriceAssumptions = {
  mode: "futures",
  market: "RS",
  loadType: "base",
  manualPriceEurPerMWh: 75,
  terminalEscalationPct: 2,
};

export const DEFAULT_SOLAR_ASSUMPTIONS: SolarAssumptions = {
  projectName: "Solar Serbia 10 MWp",
  capacityMWp: 10,
  gridMWac: 8,
  capexEurPerKWp: 750,
  fixedOpexEurPerKWYear: 12,
  variableOpexEurPerMWh: 1.5,
  degradationPct: 0.5,
  lifetimeYears: 25,
  discountRatePct: 8,
  debtSharePct: 70,
  interestRatePct: 6.5,
  loanTenorYears: 15,
  ppaPriceEurPerMWh: 65,
  revenueStructure: "hybrid",
  merchantSharePct: 30,
  curtailmentPct: 2,
  negativePriceRule: "curtail_negative",
  curtailThresholdEurPerMWh: 0,
};

export const DEFAULT_WIND_ASSUMPTIONS: WindAssumptions = {
  projectName: "Wind Serbia 100 MW",
  capacityMW: 100,
  gridMW: 100,
  netCapacityFactorPct: 32,
  capexEurPerKW: 1_350,
  fixedOpexEurPerKWYear: 38,
  variableOpexEurPerMWh: 3,
  availabilityPct: 96,
  wakeElectricalLossPct: 10,
  degradationPct: 0.2,
  lifetimeYears: 25,
  curtailmentPct: 2,
  negativePriceRule: "curtail_negative",
  curtailThresholdEurPerMWh: 0,
  ppaPriceEurPerMWh: 70,
  revenueStructure: "hybrid",
  merchantSharePct: 35,
  discountRatePct: 8,
  debtSharePct: 65,
  interestRatePct: 6.5,
  loanTenorYears: 15,
};

export const DEFAULT_BESS_ASSUMPTIONS: BessAssumptions = {
  projectName: "Serbia BESS 20 MW / 40 MWh",
  powerMW: 20,
  energyMWh: 40,
  gridImportMW: 20,
  gridExportMW: 20,
  minSocPct: 10,
  maxSocPct: 90,
  roundTripEfficiencyPct: 86,
  availabilityPct: 97,
  maxCyclesPerDay: 1,
  annualCapacityDegradationPct: 2,
  capexEurPerKW: 180,
  capexEurPerKWh: 260,
  fixedOpexEurPerKWYear: 10,
  variableThroughputEurPerMWh: 2,
  augmentationYear: 10,
  augmentationCostPct: 15,
  lifetimeYears: 20,
  revenueStructure: "hybrid",
  tollingEurPerMWYear: 45_000,
  tollingSharePct: 50,
  ancillaryEurPerMWYear: 8_000,
  discountRatePct: 9,
  debtSharePct: 50,
  interestRatePct: 7,
  loanTenorYears: 10,
};

export const DEFAULT_HYBRID_ASSUMPTIONS: HybridAssumptions = {
  projectName: "Serbia Hybrid 80 MW",
  components: "solar_wind_bess",
  solar: { ...DEFAULT_SOLAR_ASSUMPTIONS, capacityMWp: 50, gridMWac: 40 },
  wind: { ...DEFAULT_WIND_ASSUMPTIONS, capacityMW: 50, gridMW: 50 },
  bess: { ...DEFAULT_BESS_ASSUMPTIONS, powerMW: 20, energyMWh: 40 },
  sharedGridExportMW: 80,
  sharedGridImportMW: 20,
  gridChargingAllowed: true,
  chargeOnlyFromRenewables: false,
  ppaVolumeEligibleForShifting: false,
  exportAboveRenewableOutput: true,
  curtailmentRecovery: true,
  revenueStructure: "partial_ppa",
  ppaPriceEurPerMWh: 68,
  merchantSharePct: 40,
  baseloadObligationMW: 25,
  lifetimeYears: 25,
  discountRatePct: 8.5,
  debtSharePct: 60,
  interestRatePct: 6.8,
  loanTenorYears: 15,
};
