/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardWeeklyRouteImport } from './routes/dashboard.weekly'
import { Route as DashboardWeatherRouteImport } from './routes/dashboard.weather'
import { Route as DashboardWb6RouteImport } from './routes/dashboard.wb6'
import { Route as DashboardUtilizationRouteImport } from './routes/dashboard.utilization'
import { Route as DashboardSpreadsRouteImport } from './routes/dashboard.spreads'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardReportsRouteImport } from './routes/dashboard.reports'
import { Route as DashboardReportRouteImport } from './routes/dashboard.report'
import { Route as DashboardRegionalRouteImport } from './routes/dashboard.regional'
import { Route as DashboardPricesRouteImport } from './routes/dashboard.prices'
import { Route as DashboardPowerOverviewRouteImport } from './routes/dashboard.power-overview'
import { Route as DashboardPortfolioRouteImport } from './routes/dashboard.portfolio'
import { Route as DashboardOutagesRouteImport } from './routes/dashboard.outages'
import { Route as DashboardNewsRouteImport } from './routes/dashboard.news'
import { Route as DashboardMoreRouteImport } from './routes/dashboard.more'
import { Route as DashboardMethodologyRouteImport } from './routes/dashboard.methodology'
import { Route as DashboardMarketReportRouteImport } from './routes/dashboard.market-report'
import { Route as DashboardMarketRouteImport } from './routes/dashboard.market'
import { Route as DashboardMapRouteImport } from './routes/dashboard.map'
import { Route as DashboardInsightsRouteImport } from './routes/dashboard.insights'
import { Route as DashboardFuturesRouteImport } from './routes/dashboard.futures'
import { Route as DashboardForecastRouteImport } from './routes/dashboard.forecast'
import { Route as DashboardFlowsRouteImport } from './routes/dashboard.flows'
import { Route as DashboardFlexibilityRouteImport } from './routes/dashboard.flexibility'
import { Route as DashboardDanubeRouteImport } from './routes/dashboard.danube'
import { Route as DashboardCbcRouteImport } from './routes/dashboard.cbc'
import { Route as DashboardCbamRouteImport } from './routes/dashboard.cbam'
import { Route as DashboardCaptureRouteImport } from './routes/dashboard.capture'
import { Route as DashboardCapacityRouteImport } from './routes/dashboard.capacity'
import { Route as DashboardCalculatorRouteImport } from './routes/dashboard.calculator'
import { Route as DashboardBalanceRouteImport } from './routes/dashboard.balance'
import { Route as DashboardMarketsSystemRouteImport } from './routes/dashboard.markets.system'
import { Route as DashboardMarketsSpotRouteImport } from './routes/dashboard.markets.spot'
import { Route as DashboardMarketsOutlookRouteImport } from './routes/dashboard.markets.outlook'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardWeeklyRoute = DashboardWeeklyRouteImport.update({
  id: '/weekly',
  path: '/weekly',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardWeatherRoute = DashboardWeatherRouteImport.update({
  id: '/weather',
  path: '/weather',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardWb6Route = DashboardWb6RouteImport.update({
  id: '/wb6',
  path: '/wb6',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardUtilizationRoute = DashboardUtilizationRouteImport.update({
  id: '/utilization',
  path: '/utilization',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSpreadsRoute = DashboardSpreadsRouteImport.update({
  id: '/spreads',
  path: '/spreads',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardReportsRoute = DashboardReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardReportRoute = DashboardReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRegionalRoute = DashboardRegionalRouteImport.update({
  id: '/regional',
  path: '/regional',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPricesRoute = DashboardPricesRouteImport.update({
  id: '/prices',
  path: '/prices',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPowerOverviewRoute = DashboardPowerOverviewRouteImport.update({
  id: '/power-overview',
  path: '/power-overview',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPortfolioRoute = DashboardPortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardOutagesRoute = DashboardOutagesRouteImport.update({
  id: '/outages',
  path: '/outages',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardNewsRoute = DashboardNewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMoreRoute = DashboardMoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMethodologyRoute = DashboardMethodologyRouteImport.update({
  id: '/methodology',
  path: '/methodology',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMarketReportRoute = DashboardMarketReportRouteImport.update({
  id: '/market-report',
  path: '/market-report',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMarketRoute = DashboardMarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMapRoute = DashboardMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardInsightsRoute = DashboardInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardFuturesRoute = DashboardFuturesRouteImport.update({
  id: '/futures',
  path: '/futures',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardForecastRoute = DashboardForecastRouteImport.update({
  id: '/forecast',
  path: '/forecast',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardFlowsRoute = DashboardFlowsRouteImport.update({
  id: '/flows',
  path: '/flows',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardFlexibilityRoute = DashboardFlexibilityRouteImport.update({
  id: '/flexibility',
  path: '/flexibility',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDanubeRoute = DashboardDanubeRouteImport.update({
  id: '/danube',
  path: '/danube',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCbcRoute = DashboardCbcRouteImport.update({
  id: '/cbc',
  path: '/cbc',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCbamRoute = DashboardCbamRouteImport.update({
  id: '/cbam',
  path: '/cbam',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCaptureRoute = DashboardCaptureRouteImport.update({
  id: '/capture',
  path: '/capture',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCapacityRoute = DashboardCapacityRouteImport.update({
  id: '/capacity',
  path: '/capacity',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCalculatorRoute = DashboardCalculatorRouteImport.update({
  id: '/calculator',
  path: '/calculator',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBalanceRoute = DashboardBalanceRouteImport.update({
  id: '/balance',
  path: '/balance',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMarketsSystemRoute = DashboardMarketsSystemRouteImport.update({
  id: '/markets/system',
  path: '/markets/system',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMarketsSpotRoute = DashboardMarketsSpotRouteImport.update({
  id: '/markets/spot',
  path: '/markets/spot',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMarketsOutlookRoute = DashboardMarketsOutlookRouteImport.update({
  id: '/markets/outlook',
  path: '/markets/outlook',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard/balance': typeof DashboardBalanceRoute
  '/dashboard/calculator': typeof DashboardCalculatorRoute
  '/dashboard/capacity': typeof DashboardCapacityRoute
  '/dashboard/capture': typeof DashboardCaptureRoute
  '/dashboard/cbam': typeof DashboardCbamRoute
  '/dashboard/cbc': typeof DashboardCbcRoute
  '/dashboard/danube': typeof DashboardDanubeRoute
  '/dashboard/flexibility': typeof DashboardFlexibilityRoute
  '/dashboard/flows': typeof DashboardFlowsRoute
  '/dashboard/forecast': typeof DashboardForecastRoute
  '/dashboard/futures': typeof DashboardFuturesRoute
  '/dashboard/insights': typeof DashboardInsightsRoute
  '/dashboard/map': typeof DashboardMapRoute
  '/dashboard/market': typeof DashboardMarketRoute
  '/dashboard/market-report': typeof DashboardMarketReportRoute
  '/dashboard/methodology': typeof DashboardMethodologyRoute
  '/dashboard/more': typeof DashboardMoreRoute
  '/dashboard/news': typeof DashboardNewsRoute
  '/dashboard/outages': typeof DashboardOutagesRoute
  '/dashboard/portfolio': typeof DashboardPortfolioRoute
  '/dashboard/power-overview': typeof DashboardPowerOverviewRoute
  '/dashboard/prices': typeof DashboardPricesRoute
  '/dashboard/regional': typeof DashboardRegionalRoute
  '/dashboard/report': typeof DashboardReportRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/spreads': typeof DashboardSpreadsRoute
  '/dashboard/utilization': typeof DashboardUtilizationRoute
  '/dashboard/wb6': typeof DashboardWb6Route
  '/dashboard/weather': typeof DashboardWeatherRoute
  '/dashboard/weekly': typeof DashboardWeeklyRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/markets/outlook': typeof DashboardMarketsOutlookRoute
  '/dashboard/markets/spot': typeof DashboardMarketsSpotRoute
  '/dashboard/markets/system': typeof DashboardMarketsSystemRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard/balance': typeof DashboardBalanceRoute
  '/dashboard/calculator': typeof DashboardCalculatorRoute
  '/dashboard/capacity': typeof DashboardCapacityRoute
  '/dashboard/capture': typeof DashboardCaptureRoute
  '/dashboard/cbam': typeof DashboardCbamRoute
  '/dashboard/cbc': typeof DashboardCbcRoute
  '/dashboard/danube': typeof DashboardDanubeRoute
  '/dashboard/flexibility': typeof DashboardFlexibilityRoute
  '/dashboard/flows': typeof DashboardFlowsRoute
  '/dashboard/forecast': typeof DashboardForecastRoute
  '/dashboard/futures': typeof DashboardFuturesRoute
  '/dashboard/insights': typeof DashboardInsightsRoute
  '/dashboard/map': typeof DashboardMapRoute
  '/dashboard/market': typeof DashboardMarketRoute
  '/dashboard/market-report': typeof DashboardMarketReportRoute
  '/dashboard/methodology': typeof DashboardMethodologyRoute
  '/dashboard/more': typeof DashboardMoreRoute
  '/dashboard/news': typeof DashboardNewsRoute
  '/dashboard/outages': typeof DashboardOutagesRoute
  '/dashboard/portfolio': typeof DashboardPortfolioRoute
  '/dashboard/power-overview': typeof DashboardPowerOverviewRoute
  '/dashboard/prices': typeof DashboardPricesRoute
  '/dashboard/regional': typeof DashboardRegionalRoute
  '/dashboard/report': typeof DashboardReportRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/spreads': typeof DashboardSpreadsRoute
  '/dashboard/utilization': typeof DashboardUtilizationRoute
  '/dashboard/wb6': typeof DashboardWb6Route
  '/dashboard/weather': typeof DashboardWeatherRoute
  '/dashboard/weekly': typeof DashboardWeeklyRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/markets/outlook': typeof DashboardMarketsOutlookRoute
  '/dashboard/markets/spot': typeof DashboardMarketsSpotRoute
  '/dashboard/markets/system': typeof DashboardMarketsSystemRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard/balance': typeof DashboardBalanceRoute
  '/dashboard/calculator': typeof DashboardCalculatorRoute
  '/dashboard/capacity': typeof DashboardCapacityRoute
  '/dashboard/capture': typeof DashboardCaptureRoute
  '/dashboard/cbam': typeof DashboardCbamRoute
  '/dashboard/cbc': typeof DashboardCbcRoute
  '/dashboard/danube': typeof DashboardDanubeRoute
  '/dashboard/flexibility': typeof DashboardFlexibilityRoute
  '/dashboard/flows': typeof DashboardFlowsRoute
  '/dashboard/forecast': typeof DashboardForecastRoute
  '/dashboard/futures': typeof DashboardFuturesRoute
  '/dashboard/insights': typeof DashboardInsightsRoute
  '/dashboard/map': typeof DashboardMapRoute
  '/dashboard/market': typeof DashboardMarketRoute
  '/dashboard/market-report': typeof DashboardMarketReportRoute
  '/dashboard/methodology': typeof DashboardMethodologyRoute
  '/dashboard/more': typeof DashboardMoreRoute
  '/dashboard/news': typeof DashboardNewsRoute
  '/dashboard/outages': typeof DashboardOutagesRoute
  '/dashboard/portfolio': typeof DashboardPortfolioRoute
  '/dashboard/power-overview': typeof DashboardPowerOverviewRoute
  '/dashboard/prices': typeof DashboardPricesRoute
  '/dashboard/regional': typeof DashboardRegionalRoute
  '/dashboard/report': typeof DashboardReportRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/spreads': typeof DashboardSpreadsRoute
  '/dashboard/utilization': typeof DashboardUtilizationRoute
  '/dashboard/wb6': typeof DashboardWb6Route
  '/dashboard/weather': typeof DashboardWeatherRoute
  '/dashboard/weekly': typeof DashboardWeeklyRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/markets/outlook': typeof DashboardMarketsOutlookRoute
  '/dashboard/markets/spot': typeof DashboardMarketsSpotRoute
  '/dashboard/markets/system': typeof DashboardMarketsSystemRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/sitemap.xml'
    | '/dashboard/balance'
    | '/dashboard/calculator'
    | '/dashboard/capacity'
    | '/dashboard/capture'
    | '/dashboard/cbam'
    | '/dashboard/cbc'
    | '/dashboard/danube'
    | '/dashboard/flexibility'
    | '/dashboard/flows'
    | '/dashboard/forecast'
    | '/dashboard/futures'
    | '/dashboard/insights'
    | '/dashboard/map'
    | '/dashboard/market'
    | '/dashboard/market-report'
    | '/dashboard/methodology'
    | '/dashboard/more'
    | '/dashboard/news'
    | '/dashboard/outages'
    | '/dashboard/portfolio'
    | '/dashboard/power-overview'
    | '/dashboard/prices'
    | '/dashboard/regional'
    | '/dashboard/report'
    | '/dashboard/reports'
    | '/dashboard/settings'
    | '/dashboard/spreads'
    | '/dashboard/utilization'
    | '/dashboard/wb6'
    | '/dashboard/weather'
    | '/dashboard/weekly'
    | '/dashboard/'
    | '/dashboard/markets/outlook'
    | '/dashboard/markets/spot'
    | '/dashboard/markets/system'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sitemap.xml'
    | '/dashboard/balance'
    | '/dashboard/calculator'
    | '/dashboard/capacity'
    | '/dashboard/capture'
    | '/dashboard/cbam'
    | '/dashboard/cbc'
    | '/dashboard/danube'
    | '/dashboard/flexibility'
    | '/dashboard/flows'
    | '/dashboard/forecast'
    | '/dashboard/futures'
    | '/dashboard/insights'
    | '/dashboard/map'
    | '/dashboard/market'
    | '/dashboard/market-report'
    | '/dashboard/methodology'
    | '/dashboard/more'
    | '/dashboard/news'
    | '/dashboard/outages'
    | '/dashboard/portfolio'
    | '/dashboard/power-overview'
    | '/dashboard/prices'
    | '/dashboard/regional'
    | '/dashboard/report'
    | '/dashboard/reports'
    | '/dashboard/settings'
    | '/dashboard/spreads'
    | '/dashboard/utilization'
    | '/dashboard/wb6'
    | '/dashboard/weather'
    | '/dashboard/weekly'
    | '/dashboard'
    | '/dashboard/markets/outlook'
    | '/dashboard/markets/spot'
    | '/dashboard/markets/system'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/sitemap.xml'
    | '/dashboard/balance'
    | '/dashboard/calculator'
    | '/dashboard/capacity'
    | '/dashboard/capture'
    | '/dashboard/cbam'
    | '/dashboard/cbc'
    | '/dashboard/danube'
    | '/dashboard/flexibility'
    | '/dashboard/flows'
    | '/dashboard/forecast'
    | '/dashboard/futures'
    | '/dashboard/insights'
    | '/dashboard/map'
    | '/dashboard/market'
    | '/dashboard/market-report'
    | '/dashboard/methodology'
    | '/dashboard/more'
    | '/dashboard/news'
    | '/dashboard/outages'
    | '/dashboard/portfolio'
    | '/dashboard/power-overview'
    | '/dashboard/prices'
    | '/dashboard/regional'
    | '/dashboard/report'
    | '/dashboard/reports'
    | '/dashboard/settings'
    | '/dashboard/spreads'
    | '/dashboard/utilization'
    | '/dashboard/wb6'
    | '/dashboard/weather'
    | '/dashboard/weekly'
    | '/dashboard/'
    | '/dashboard/markets/outlook'
    | '/dashboard/markets/spot'
    | '/dashboard/markets/system'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/weekly': {
      id: '/dashboard/weekly'
      path: '/weekly'
      fullPath: '/dashboard/weekly'
      preLoaderRoute: typeof DashboardWeeklyRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/weather': {
      id: '/dashboard/weather'
      path: '/weather'
      fullPath: '/dashboard/weather'
      preLoaderRoute: typeof DashboardWeatherRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/wb6': {
      id: '/dashboard/wb6'
      path: '/wb6'
      fullPath: '/dashboard/wb6'
      preLoaderRoute: typeof DashboardWb6RouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/utilization': {
      id: '/dashboard/utilization'
      path: '/utilization'
      fullPath: '/dashboard/utilization'
      preLoaderRoute: typeof DashboardUtilizationRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/spreads': {
      id: '/dashboard/spreads'
      path: '/spreads'
      fullPath: '/dashboard/spreads'
      preLoaderRoute: typeof DashboardSpreadsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/reports': {
      id: '/dashboard/reports'
      path: '/reports'
      fullPath: '/dashboard/reports'
      preLoaderRoute: typeof DashboardReportsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/report': {
      id: '/dashboard/report'
      path: '/report'
      fullPath: '/dashboard/report'
      preLoaderRoute: typeof DashboardReportRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/regional': {
      id: '/dashboard/regional'
      path: '/regional'
      fullPath: '/dashboard/regional'
      preLoaderRoute: typeof DashboardRegionalRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/prices': {
      id: '/dashboard/prices'
      path: '/prices'
      fullPath: '/dashboard/prices'
      preLoaderRoute: typeof DashboardPricesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/power-overview': {
      id: '/dashboard/power-overview'
      path: '/power-overview'
      fullPath: '/dashboard/power-overview'
      preLoaderRoute: typeof DashboardPowerOverviewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/portfolio': {
      id: '/dashboard/portfolio'
      path: '/portfolio'
      fullPath: '/dashboard/portfolio'
      preLoaderRoute: typeof DashboardPortfolioRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/outages': {
      id: '/dashboard/outages'
      path: '/outages'
      fullPath: '/dashboard/outages'
      preLoaderRoute: typeof DashboardOutagesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/news': {
      id: '/dashboard/news'
      path: '/news'
      fullPath: '/dashboard/news'
      preLoaderRoute: typeof DashboardNewsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/more': {
      id: '/dashboard/more'
      path: '/more'
      fullPath: '/dashboard/more'
      preLoaderRoute: typeof DashboardMoreRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/methodology': {
      id: '/dashboard/methodology'
      path: '/methodology'
      fullPath: '/dashboard/methodology'
      preLoaderRoute: typeof DashboardMethodologyRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/market-report': {
      id: '/dashboard/market-report'
      path: '/market-report'
      fullPath: '/dashboard/market-report'
      preLoaderRoute: typeof DashboardMarketReportRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/market': {
      id: '/dashboard/market'
      path: '/market'
      fullPath: '/dashboard/market'
      preLoaderRoute: typeof DashboardMarketRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/map': {
      id: '/dashboard/map'
      path: '/map'
      fullPath: '/dashboard/map'
      preLoaderRoute: typeof DashboardMapRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/insights': {
      id: '/dashboard/insights'
      path: '/insights'
      fullPath: '/dashboard/insights'
      preLoaderRoute: typeof DashboardInsightsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/futures': {
      id: '/dashboard/futures'
      path: '/futures'
      fullPath: '/dashboard/futures'
      preLoaderRoute: typeof DashboardFuturesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/forecast': {
      id: '/dashboard/forecast'
      path: '/forecast'
      fullPath: '/dashboard/forecast'
      preLoaderRoute: typeof DashboardForecastRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/flows': {
      id: '/dashboard/flows'
      path: '/flows'
      fullPath: '/dashboard/flows'
      preLoaderRoute: typeof DashboardFlowsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/flexibility': {
      id: '/dashboard/flexibility'
      path: '/flexibility'
      fullPath: '/dashboard/flexibility'
      preLoaderRoute: typeof DashboardFlexibilityRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/danube': {
      id: '/dashboard/danube'
      path: '/danube'
      fullPath: '/dashboard/danube'
      preLoaderRoute: typeof DashboardDanubeRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/cbc': {
      id: '/dashboard/cbc'
      path: '/cbc'
      fullPath: '/dashboard/cbc'
      preLoaderRoute: typeof DashboardCbcRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/cbam': {
      id: '/dashboard/cbam'
      path: '/cbam'
      fullPath: '/dashboard/cbam'
      preLoaderRoute: typeof DashboardCbamRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/capture': {
      id: '/dashboard/capture'
      path: '/capture'
      fullPath: '/dashboard/capture'
      preLoaderRoute: typeof DashboardCaptureRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/capacity': {
      id: '/dashboard/capacity'
      path: '/capacity'
      fullPath: '/dashboard/capacity'
      preLoaderRoute: typeof DashboardCapacityRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/calculator': {
      id: '/dashboard/calculator'
      path: '/calculator'
      fullPath: '/dashboard/calculator'
      preLoaderRoute: typeof DashboardCalculatorRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/balance': {
      id: '/dashboard/balance'
      path: '/balance'
      fullPath: '/dashboard/balance'
      preLoaderRoute: typeof DashboardBalanceRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/markets/system': {
      id: '/dashboard/markets/system'
      path: '/markets/system'
      fullPath: '/dashboard/markets/system'
      preLoaderRoute: typeof DashboardMarketsSystemRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/markets/spot': {
      id: '/dashboard/markets/spot'
      path: '/markets/spot'
      fullPath: '/dashboard/markets/spot'
      preLoaderRoute: typeof DashboardMarketsSpotRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/markets/outlook': {
      id: '/dashboard/markets/outlook'
      path: '/markets/outlook'
      fullPath: '/dashboard/markets/outlook'
      preLoaderRoute: typeof DashboardMarketsOutlookRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardBalanceRoute: typeof DashboardBalanceRoute
  DashboardCalculatorRoute: typeof DashboardCalculatorRoute
  DashboardCapacityRoute: typeof DashboardCapacityRoute
  DashboardCaptureRoute: typeof DashboardCaptureRoute
  DashboardCbamRoute: typeof DashboardCbamRoute
  DashboardCbcRoute: typeof DashboardCbcRoute
  DashboardDanubeRoute: typeof DashboardDanubeRoute
  DashboardFlexibilityRoute: typeof DashboardFlexibilityRoute
  DashboardFlowsRoute: typeof DashboardFlowsRoute
  DashboardForecastRoute: typeof DashboardForecastRoute
  DashboardFuturesRoute: typeof DashboardFuturesRoute
  DashboardInsightsRoute: typeof DashboardInsightsRoute
  DashboardMapRoute: typeof DashboardMapRoute
  DashboardMarketRoute: typeof DashboardMarketRoute
  DashboardMarketReportRoute: typeof DashboardMarketReportRoute
  DashboardMethodologyRoute: typeof DashboardMethodologyRoute
  DashboardMoreRoute: typeof DashboardMoreRoute
  DashboardNewsRoute: typeof DashboardNewsRoute
  DashboardOutagesRoute: typeof DashboardOutagesRoute
  DashboardPortfolioRoute: typeof DashboardPortfolioRoute
  DashboardPowerOverviewRoute: typeof DashboardPowerOverviewRoute
  DashboardPricesRoute: typeof DashboardPricesRoute
  DashboardRegionalRoute: typeof DashboardRegionalRoute
  DashboardReportRoute: typeof DashboardReportRoute
  DashboardReportsRoute: typeof DashboardReportsRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardSpreadsRoute: typeof DashboardSpreadsRoute
  DashboardUtilizationRoute: typeof DashboardUtilizationRoute
  DashboardWb6Route: typeof DashboardWb6Route
  DashboardWeatherRoute: typeof DashboardWeatherRoute
  DashboardWeeklyRoute: typeof DashboardWeeklyRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardMarketsOutlookRoute: typeof DashboardMarketsOutlookRoute
  DashboardMarketsSpotRoute: typeof DashboardMarketsSpotRoute
  DashboardMarketsSystemRoute: typeof DashboardMarketsSystemRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardBalanceRoute: DashboardBalanceRoute,
  DashboardCalculatorRoute: DashboardCalculatorRoute,
  DashboardCapacityRoute: DashboardCapacityRoute,
  DashboardCaptureRoute: DashboardCaptureRoute,
  DashboardCbamRoute: DashboardCbamRoute,
  DashboardCbcRoute: DashboardCbcRoute,
  DashboardDanubeRoute: DashboardDanubeRoute,
  DashboardFlexibilityRoute: DashboardFlexibilityRoute,
  DashboardFlowsRoute: DashboardFlowsRoute,
  DashboardForecastRoute: DashboardForecastRoute,
  DashboardFuturesRoute: DashboardFuturesRoute,
  DashboardInsightsRoute: DashboardInsightsRoute,
  DashboardMapRoute: DashboardMapRoute,
  DashboardMarketRoute: DashboardMarketRoute,
  DashboardMarketReportRoute: DashboardMarketReportRoute,
  DashboardMethodologyRoute: DashboardMethodologyRoute,
  DashboardMoreRoute: DashboardMoreRoute,
  DashboardNewsRoute: DashboardNewsRoute,
  DashboardOutagesRoute: DashboardOutagesRoute,
  DashboardPortfolioRoute: DashboardPortfolioRoute,
  DashboardPowerOverviewRoute: DashboardPowerOverviewRoute,
  DashboardPricesRoute: DashboardPricesRoute,
  DashboardRegionalRoute: DashboardRegionalRoute,
  DashboardReportRoute: DashboardReportRoute,
  DashboardReportsRoute: DashboardReportsRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardSpreadsRoute: DashboardSpreadsRoute,
  DashboardUtilizationRoute: DashboardUtilizationRoute,
  DashboardWb6Route: DashboardWb6Route,
  DashboardWeatherRoute: DashboardWeatherRoute,
  DashboardWeeklyRoute: DashboardWeeklyRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardMarketsOutlookRoute: DashboardMarketsOutlookRoute,
  DashboardMarketsSpotRoute: DashboardMarketsSpotRoute,
  DashboardMarketsSystemRoute: DashboardMarketsSystemRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
