// This file is automatically generated. Do not edit it directly.
// Server-side Supabase client with service role key - bypasses RLS.
// Use this for trusted server functions and server routes only.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

type NoopQuery = {
  select: () => NoopQuery;
  eq: () => NoopQuery;
  gte: () => NoopQuery;
  lte: () => NoopQuery;
  order: () => NoopQuery;
  limit: () => NoopQuery;
  range: () => Promise<{ data: []; error: null }>;
  insert: () => Promise<{ data: null; error: null }>;
  update: () => NoopQuery;
  delete: () => NoopQuery;
  upsert: () => Promise<{ data: null; error: null }>;
  maybeSingle: () => Promise<{ data: null; error: null }>;
  single: () => Promise<{ data: null; error: null }>;
};

function createNoopSupabaseAdminClient() {
  const createQuery = (): NoopQuery => {
    const query: NoopQuery = {
      select: () => query,
      eq: () => query,
      gte: () => query,
      lte: () => query,
      order: () => query,
      limit: () => query,
      range: async () => ({ data: [], error: null }),
      insert: async () => ({ data: null, error: null }),
      update: () => query,
      delete: () => query,
      upsert: async () => ({ data: null, error: null }),
      maybeSingle: async () => ({ data: null, error: null }),
      single: async () => ({ data: null, error: null }),
    };
    return query;
  };

  return {
    from: () => createQuery(),
  } as unknown as ReturnType<typeof createSupabaseAdminClient>;
}

function createSupabaseAdminClient() {
  const SUPABASE_URL = process.env.SUPABASE_URL;
  const SUPABASE_SERVICE_ROLE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY;

  if (!SUPABASE_URL || !SUPABASE_SERVICE_ROLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ["SUPABASE_URL"] : []),
      ...(!SUPABASE_SERVICE_ROLE_KEY ? ["SUPABASE_SERVICE_ROLE_KEY"] : []),
    ];
    console.warn(
      `[Supabase] Missing ${missing.join(", ")}. Server-side cache/database features are disabled; pages will show unavailable states.`,
    );
    return createNoopSupabaseAdminClient();
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY, {
    auth: {
      storage: undefined,
      persistSession: false,
      autoRefreshToken: false,
    },
  });
}

let _supabaseAdmin: ReturnType<typeof createSupabaseAdminClient> | undefined;

export const supabaseAdmin = new Proxy({} as ReturnType<typeof createSupabaseAdminClient>, {
  get(_, prop, receiver) {
    if (!_supabaseAdmin) _supabaseAdmin = createSupabaseAdminClient();
    return Reflect.get(_supabaseAdmin, prop, receiver);
  },
});
