// This file is automatically generated. Do not edit it directly.
// Server-side Supabase client with service role key - bypasses RLS.
// Use this for trusted server functions and server routes only.
import { createClient, type SupabaseClient } from "@supabase/supabase-js";

// The project URL is public configuration. The service-role key remains
// environment-only and is never embedded in source.
const PUBLIC_SUPABASE_URL = "https://ialzzzzyqsnylbkeufsu.supabase.co";

// Server admin queries touch migration-backed tables that can be ahead of generated client types.
// eslint-disable-next-line @typescript-eslint/no-explicit-any
type SupabaseAdminClient = SupabaseClient<any>;

type NoopQuery = {
  select: () => NoopQuery;
  eq: () => NoopQuery;
  gte: () => NoopQuery;
  lte: () => NoopQuery;
  order: () => NoopQuery;
  limit: () => NoopQuery;
  range: () => Promise<{ data: []; error: null }>;
  insert: () => Promise<{ data: null; error: null }>;
  update: () => NoopQuery;
  delete: () => NoopQuery;
  upsert: () => Promise<{ data: null; error: null }>;
  maybeSingle: () => Promise<{ data: null; error: null }>;
  single: () => Promise<{ data: null; error: null }>;
};

function createNoopSupabaseAdminClient(): SupabaseAdminClient {
  const createQuery = (): NoopQuery => {
    const query: NoopQuery = {
      select: () => query,
      eq: () => query,
      gte: () => query,
      lte: () => query,
      order: () => query,
      limit: () => query,
      range: async () => ({ data: [], error: null }),
      insert: async () => ({ data: null, error: null }),
      update: () => query,
      delete: () => query,
      upsert: async () => ({ data: null, error: null }),
      maybeSingle: async () => ({ data: null, error: null }),
      single: async () => ({ data: null, error: null }),
    };
    return query;
  };

  return {
    from: () => createQuery(),
  } as unknown as SupabaseAdminClient;
}

function createSupabaseAdminClient(): SupabaseAdminClient {
  const SUPABASE_URL = process.env.SUPABASE_URL || PUBLIC_SUPABASE_URL;
  const SUPABASE_SERVICE_ROLE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY;

  if (!SUPABASE_SERVICE_ROLE_KEY) {
    console.warn(
      "[Supabase] Missing SUPABASE_SERVICE_ROLE_KEY. Server-side cache/database features are disabled; live upstream reads can still operate.",
    );
    return createNoopSupabaseAdminClient();
  }

  return createClient(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY, {
    auth: {
      storage: undefined,
      persistSession: false,
      autoRefreshToken: false,
    },
  });
}

let _supabaseAdmin: SupabaseAdminClient | undefined;

export const supabaseAdmin = new Proxy({} as SupabaseAdminClient, {
  get(_, prop, receiver) {
    if (!_supabaseAdmin) _supabaseAdmin = createSupabaseAdminClient();
    return Reflect.get(_supabaseAdmin, prop, receiver);
  },
});
